### ISSUE TITLE
HEE and Defective recipes

### ISSUE THREAD

**Issue by SkySom** [ScottDTA/ExtraCarts-1.7.10#11]
https://app.box.com/s/r7u672vinvdzzt919pnxisyznrbjzy4h

There are currently issues with the Leaded Minecart which causes crashes due to defective recipes in 0.8.0

**Comment by Amaxter** [comment]
Yeah, been noticing the same thing and had to set it to override them in the config: http://hastebin.com/husutetupi.xml

**Comment by SkySom** [comment]
@Amaxter mind doing me a favor and sending me the full log. I've not gotten it to break for me, so the more information I have, the better.

**Comment by Amaxter** [comment]
With the config for HEE set to ignore so game doesn't crash these are my logs:
http://hastebin.com/cekebiyera.vbs
