### ISSUE TITLE
Perhaps collab w/ ganymedes01?

### ISSUE THREAD

**Issue by T145** [ScottDTA/ExtraCarts-1.7.10#12]
He's doing something similar w/ his [IronChestMinecarts](https://github.com/ganymedes01/IronChestMinecarts) mod. Maybe you can help each other out!

**Comment by SkySom** [comment]
Slightly similar. While we also have an Ironchests module. We expanded passed that to other stuff. His may be best for those that just want Iron Chests stuff.
