### ISSUE TITLE
Wrong texture after upgrade silver chest to gold chest

### ISSUE THREAD

**Issue by vrnRaptor** [ScottDTA/ExtraCarts-1.7.10#15]
Wrong texture after upgrade silver chest to gold chest:
![2016-11-06_20 38 52](https://cloud.githubusercontent.com/assets/13599993/20040094/36400220-a462-11e6-9bc9-8792fe3bc2e8.png)

**Comment by SkySom** [comment]
This mod is abandon. Please us MoarCarts for 1.7.10/1.8.9 and OpenTransport when it is released for 1.10.2
